// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okzgwxboyibsfdncwmpn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9remd3eGJveWlic2ZkbmN3bXBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1NjQ2NjIsImV4cCI6MjA3NjE0MDY2Mn0.vetY7ic8gxBbPA880-Vimxxo_IdQxwn99FlH6J4Zggc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});